colors = [
    "cloudy blue",
    "dark pastel green",
    "dust",
    "electric lime",
    "fresh green",
    "light eggplant",
    "nasty green",
    "really light blue",
    "tea",
    "warm purple",
    "yellowish tan",
    "cement",
    "dark grass green",
    "dusty teal",
    "grey teal",
    "macaroni and cheese",
    "pinkish tan",
    "spruce",
    "strong blue",
    "toxic green",
    "windows blue",
    "blue blue",
    "blue with a hint of purple",
    "booger",
    "bright sea green",
    "dark green blue",
    "deep turquoise",
    "green teal",
    "strong pink",
    "bland",
    "deep aqua",
    "lavender pink",
    "light moss green",
    "light seafoam green",
    "olive yellow",
    "pig pink",
    "deep lilac",
    "desert",
    "dusty lavender",
    "purpley grey",
    "purply",
    "candy pink",
    "light pastel green",
    "boring green",
    "kiwi green",
    "light grey green",
    "orange pink",
    "tea green",
    "very light brown",
    "egg shell",
    "eggplant purple",
    "powder pink",
    "reddish grey",
    "baby shit brown",
    "liliac",
    "stormy blue",
    "ugly brown",
    "custard",
    "darkish pink",
    "deep brown",
    "greenish beige",
    "manilla",
    "off blue",
    "battleship grey",
    "browny green",
    "bruise",
    "kelley green",
    "sickly yellow",
    "sunny yellow",
    "azul",
    "darkgreen",
    "green/yellow",
    "lichen",
    "light light green",
    "pale gold",
    "sun yellow",
    "tan green",
    "burple",
    "butterscotch",
    "toupe",
    "dark cream",
    "indian red",
    "light lavendar",
    "poison green",
    "baby puke green",
    "bright yellow green",
    "charcoal grey",
    "squash",
    "cinnamon",
    "light pea green",
    "radioactive green",
    "raw sienna",
    "baby purple",
    "cocoa",
    "light royal blue",
    "orangeish",
    "rust brown",
    "sand brown",
    "swamp",
    "tealish green",
    "burnt siena",
    "camo",
    "dusk blue",
    "fern",
    "old rose",
    "pale light green",
    "peachy pink",
    "rosy pink",
    "light bluish green",
    "light bright green",
    "light neon green",
    "light seafoam",
    "tiffany blue",
    "washed out green",
    "browny orange",
    "nice blue",
    "sapphire",
    "greyish teal",
    "orangey yellow",
    "parchment",
    "straw",
    "very dark brown",
    "terracota",
    "ugly blue",
    "clear blue",
    "creme",
    "foam green",
    "grey/green",
    "light gold",
    "seafoam blue",
    "topaz",
    "violet pink",
    "wintergreen",
    "yellow tan",
    "dark fuchsia",
    "indigo blue",
    "light yellowish green",
    "pale magenta",
    "rich purple",
    "sunflower yellow",
    "green/blue",
    "leather",
    "racing green",
    "vivid purple",
    "dark royal blue",
    "hazel",
    "muted pink",
    "booger green",
    "canary",
    "cool grey",
    "dark taupe",
    "darkish purple",
    "true green",
    "coral pink",
    "dark sage",
    "dark slate blue",
    "flat blue",
    "mushroom",
    "rich blue",
    "dirty purple",
    "greenblue",
    "icky green",
    "light khaki",
    "warm blue",
    "dark hot pink",
    "deep sea blue",
    "carmine",
    "dark yellow green",
    "pale peach",
    "plum purple",
    "golden rod",
    "neon red",
    "old pink",
    "very pale blue",
    "blood orange",
    "grapefruit",
    "sand yellow",
    "clay brown",
    "dark blue grey",
    "flat green",
    "light green blue",
    "warm pink",
    "dodger blue",
    "gross green",
    "ice",
    "metallic blue",
    "pale salmon",
    "sap green",
    "algae",
    "bluey grey",
    "greeny grey",
    "highlighter green",
    "light light blue",
    "light mint",
    "raw umber",
    "vivid blue",
    "deep lavender",
    "dull teal",
    "light greenish blue",
    "mud green",
    "pinky",
    "red wine",
    "shit green",
    "tan brown",
    "darkblue",
    "rosa",
    "lipstick",
    "pale mauve",
    "claret",
    "dandelion",
    "orangered",
    "poop green",
    "ruby",
    "dark",
    "greenish turquoise",
    "pastel red",
    "piss yellow",
    "bright cyan",
    "dark coral",
    "algae green",
    "darkish red",
    "reddy brown",
    "blush pink",
    "camouflage green",
    "lawn green",
    "putty",
    "vibrant blue",
    "dark sand",
    "purple/blue",
    "saffron",
    "twilight",
    "warm brown",
    "bluegrey",
    "bubble gum pink",
    "duck egg blue",
    "greenish cyan",
    "petrol",
    "royal",
    "butter",
    "dusty orange",
    "off yellow",
    "pale olive green",
    "orangish",
    "leaf",
    "light blue grey",
    "dried blood",
    "lightish purple",
    "rusty red",
    "lavender blue",
    "light grass green",
    "light mint green",
    "sunflower",
    "velvet",
    "brick orange",
    "lightish red",
    "pure blue",
    "twilight blue",
    "violet red",
    "yellowy brown",
    "carnation",
    "muddy yellow",
    "dark seafoam green",
    "deep rose",
    "dusty red",
    "grey/blue",
    "lemon lime",
    "purple/pink",
    "brown yellow",
    "purple brown",
    "wisteria",
    "banana yellow",
    "lipstick red",
    "water blue",
    "brown grey",
    "vibrant purple",
    "baby green",
    "barf green",
    "eggshell blue",
    "sandy yellow",
    "cool green",
    "pale",
    "blue/grey",
    "hot magenta",
    "greyblue",
    "purpley",
    "baby shit green",
    "brownish pink",
    "dark aquamarine",
    "diarrhea",
    "light mustard",
    "pale sky blue",
    "turtle green",
    "bright olive",
    "dark grey blue",
    "greeny brown",
    "lemon green",
    "light periwinkle",
    "seaweed green",
    "sunshine yellow",
    "ugly purple",
    "medium pink",
    "puke brown",
    "very light pink",
    "viridian",
    "bile",
    "faded yellow",
    "very pale green",
    "vibrant green",
    "bright lime",
    "spearmint",
    "light aquamarine",
    "light sage",
    "yellowgreen",
    "baby poo",
    "dark seafoam",
    "deep teal",
    "heather",
    "rust orange",
    "dirty blue",
    "fern green",
    "bright lilac",
    "weird green",
    "peacock blue",
    "avocado green",
    "faded orange",
    "grape purple",
    "hot green",
    "lime yellow",
    "mango",
    "shamrock",
    "bubblegum",
    "purplish brown",
    "vomit yellow",
    "pale cyan",
    "key lime",
    "tomato red",
    "lightgreen",
    "merlot",
    "night blue",
    "purpleish pink",
    "apple",
    "baby poop green",
    "green apple",
    "heliotrope",
    "yellow/green",
    "almost black",
    "cool blue",
    "leafy green",
    "mustard brown",
    "dusk",
    "dull brown",
    "frog green",
    "vivid green",
    "bright light green",
    "fluro green",
    "kiwi",
    "seaweed",
    "navy green",
    "ultramarine blue",
    "iris",
    "pastel orange",
    "yellowish orange",
    "perrywinkle",
    "tealish",
    "dark plum",
    "pear",
    "pinkish orange",
    "midnight purple",
    "light urple",
    "dark mint",
    "greenish tan",
    "light burgundy",
    "turquoise blue",
    "ugly pink",
    "sandy",
    "electric pink",
    "muted purple",
    "mid green",
    "greyish",
    "neon yellow",
    "banana",
    "carnation pink",
    "tomato",
    "sea",
    "muddy brown",
    "turquoise green",
    "buff",
    "fawn",
    "muted blue",
    "pale rose",
    "dark mint green",
    "amethyst",
    "blue/green",
    "chestnut",
    "sick green",
    "pea",
    "rusty orange",
    "stone",
    "rose red",
    "pale aqua",
    "deep orange",
    "earth",
    "mossy green",
    "grassy green",
    "pale lime green",
    "light grey blue",
    "pale grey",
    "asparagus",
    "blueberry",
    "purple red",
    "pale lime",
    "greenish teal",
    "caramel",
    "deep magenta",
    "light peach",
    "milk chocolate",
    "ocher",
    "off green",
    "purply pink",
    "lightblue",
    "dusky blue",
    "golden",
    "light beige",
    "butter yellow",
    "dusky purple",
    "french blue",
    "ugly yellow",
    "greeny yellow",
    "orangish red",
    "shamrock green",
    "orangish brown",
    "tree green",
    "deep violet",
    "gunmetal",
    "blue/purple",
    "cherry",
    "sandy brown",
    "warm grey",
    "dark indigo",
    "midnight",
    "bluey green",
    "grey pink",
    "soft purple",
    "blood",
    "brown red",
    "medium grey",
    "berry",
    "poo",
    "purpley pink",
    "light salmon",
    "snot",
    "easter purple",
    "light yellow green",
    "dark navy blue",
    "drab",
    "light rose",
    "rouge",
    "purplish red",
    "slime green",
    "baby poop",
    "irish green",
    "pink/purple",
    "dark navy",
    "greeny blue",
    "light plum",
    "pinkish grey",
    "dirty orange",
    "rust red",
    "pale lilac",
    "orangey red",
    "primary blue",
    "kermit green",
    "brownish purple",
    "murky green",
    "wheat",
    "very dark purple",
    "bottle green",
    "watermelon",
    "deep sky blue",
    "fire engine red",
    "yellow ochre",
    "pumpkin orange",
    "pale olive",
    "light lilac",
    "lightish green",
    "carolina blue",
    "mulberry",
    "shocking pink",
    "auburn",
    "bright lime green",
    "celadon",
    "pinkish brown",
    "poo brown",
    "bright sky blue",
    "celery",
    "dirt brown",
    "strawberry",
    "dark lime",
    "copper",
    "medium brown",
    "muted green",
    "robin's egg",
    "bright aqua",
    "bright lavender",
    "ivory",
    "very light purple",
    "light navy",
    "pink red",
    "olive brown",
    "poop brown",
    "mustard green",
    "ocean green",
    "very dark blue",
    "dusty green",
    "light navy blue",
    "minty green",
    "adobe",
    "barney",
    "jade green",
    "bright light blue",
    "light lime",
    "dark khaki",
    "orange yellow",
    "ocre",
    "maize",
    "faded pink",
    "british racing green",
    "sandstone",
    "mud brown",
    "light sea green",
    "robin egg blue",
    "aqua marine",
    "dark sea green",
    "soft pink",
    "orangey brown",
    "cherry red",
    "burnt yellow",
    "brownish grey",
    "camel",
    "purplish grey",
    "marine",
    "greyish pink",
    "pale turquoise",
    "pastel yellow",
    "bluey purple",
    "canary yellow",
    "faded red",
    "sepia",
    "coffee",
    "bright magenta",
    "mocha",
    "ecru",
    "purpleish",
    "cranberry",
    "darkish green",
    "brown orange",
    "dusky rose",
    "melon",
    "sickly green",
    "silver",
    "purply blue",
    "purpleish blue",
    "hospital green",
    "shit brown",
    "mid blue",
    "amber",
    "easter green",
    "soft blue",
    "cerulean blue",
    "golden brown",
    "bright turquoise",
    "red pink",
    "red purple",
    "greyish brown",
    "vermillion",
    "russet",
    "steel grey",
    "lighter purple",
    "bright violet",
    "prussian blue",
    "slate green",
    "dirty pink",
    "dark blue green",
    "pine",
    "yellowy green",
    "dark gold",
    "bluish",
    "darkish blue",
    "dull red",
    "pinky red",
    "bronze",
    "pale teal",
    "military green",
    "barbie pink",
    "bubblegum pink",
    "pea soup green",
    "dark mustard",
    "shit",
    "medium purple",
    "very dark green",
    "dirt",
    "dusky pink",
    "red violet",
    "lemon yellow",
    "pistachio",
    "dull yellow",
    "dark lime green",
    "denim blue",
    "teal blue",
    "lightish blue",
    "purpley blue",
    "light indigo",
    "swamp green",
    "brown green",
    "dark maroon",
    "hot purple",
    "dark forest green",
    "faded blue",
    "drab green",
    "light lime green",
    "snot green",
    "yellowish",
    "light blue green",
    "bordeaux",
    "light mauve",
    "ocean",
    "marigold",
    "muddy green",
    "dull orange",
    "steel",
    "electric purple",
    "fluorescent green",
    "yellowish brown",
    "blush",
    "soft green",
    "bright orange",
    "lemon",
    "purple grey",
    "acid green",
    "pale lavender",
    "violet blue",
    "light forest green",
    "burnt red",
    "khaki green",
    "cerise",
    "faded purple",
    "apricot",
    "dark olive green",
    "grey brown",
    "green grey",
    "true blue",
    "pale violet",
    "periwinkle blue",
    "light sky blue",
    "blurple",
    "green brown",
    "bluegreen",
    "bright teal",
    "brownish yellow",
    "pea soup",
    "forest",
    "barney purple",
    "ultramarine",
    "purplish",
    "puke yellow",
    "bluish grey",
    "dark periwinkle",
    "dark lilac",
    "reddish",
    "light maroon",
    "dusty purple",
    "terra cotta",
    "avocado",
    "marine blue",
    "teal green",
    "slate grey",
    "lighter green",
    "electric green",
    "dusty blue",
    "golden yellow",
    "bright yellow",
    "light lavender",
    "umber",
    "poop",
    "dark peach",
    "jungle green",
    "eggshell",
    "denim",
    "yellow brown",
    "dull purple",
    "chocolate brown",
    "wine red",
    "neon blue",
    "dirty green",
    "light tan",
    "ice blue",
    "cadet blue",
    "dark mauve",
    "very light blue",
    "grey purple",
    "pastel pink",
    "very light green",
    "dark sky blue",
    "evergreen",
    "dull pink",
    "aubergine",
    "mahogany",
    "reddish orange",
    "deep green",
    "vomit green",
    "purple pink",
    "dusty pink",
    "faded green",
    "camo green",
    "pinky purple",
    "pink purple",
    "brownish red",
    "dark rose",
    "mud",
    "brownish",
    "emerald green",
    "pale brown",
    "dull blue",
    "burnt umber",
    "medium green",
    "clay",
    "light aqua",
    "light olive green",
    "brownish orange",
    "dark aqua",
    "purplish pink",
    "dark salmon",
    "greenish grey",
    "jade",
    "ugly green",
    "dark beige",
    "emerald",
    "pale red",
    "light magenta",
    "sky",
    "light cyan",
    "yellow orange",
    "reddish purple",
    "reddish pink",
    "orchid",
    "dirty yellow",
    "orange red",
    "deep red",
    "orange brown",
    "cobalt blue",
    "neon pink",
    "rose pink",
    "greyish purple",
    "raspberry",
    "aqua green",
    "salmon pink",
    "tangerine",
    "brownish green",
    "red brown",
    "greenish brown",
    "pumpkin",
    "pine green",
    "charcoal",
    "baby pink",
    "cornflower",
    "blue violet",
    "chocolate",
    "greyish green",
    "scarlet",
    "green yellow",
    "dark olive",
    "sienna",
    "pastel purple",
    "terracotta",
    "aqua blue",
    "sage green",
    "blood red",
    "deep pink",
    "grass",
    "moss",
    "pastel blue",
    "bluish green",
    "green blue",
    "dark tan",
    "greenish blue",
    "pale orange",
    "vomit",
    "forrest green",
    "dark lavender",
    "dark violet",
    "purple blue",
    "dark cyan",
    "olive drab",
    "pinkish",
    "cobalt",
    "neon purple",
    "light turquoise",
    "apple green",
    "dull green",
    "wine",
    "powder blue",
    "off white",
    "electric blue",
    "dark turquoise",
    "blue purple",
    "azure",
    "bright ",
    "pinkish red",
    "cornflower blue",
    "light olive",
    "grape",
    "greyish blue",
    "purplish blue",
    "yellowish green",
    "greenish yellow",
    "medium blue",
    "dusty rose",
    "light violet",
    "midnight blue",
    "bluish purple",
    "red orange",
    "dark magenta",
    "greenish",
    "ocean blue",
    "coral",
    "cream",
    "reddish brown",
    "burnt sienna",
    "brick",
    "sage",
    "grey green",
    "white",
    "robin's egg blue",
    "moss green",
    "steel blue",
    "eggplant",
    "light yellow",
    "leaf green",
    "light grey",
    "puke",
    "pinkish purple",
    "sea blue",
    "pale purple",
    "slate blue",
    "blue grey",
    "hunter green",
    "fuchsia",
    "crimson",
    "pale yellow",
    "ochre",
    "mustard yellow",
    "light red",
    "cerulean",
    "pale pink",
    "deep blue",
    "rust",
    "light teal",
    "slate",
    "goldenrod",
    "dark yellow",
    "dark grey",
    "army green",
    "grey blue",
    "seafoam",
    "puce",
    "spring green",
    "dark orange",
    "sand",
    "pastel green",
    "mint",
    "light orange",
    "bright pink",
    "chartreuse",
    "deep purple",
    "dark brown",
    "taupe",
    "pea green",
    "puke green",
    "kelly green",
    "seafoam green",
    "blue green",
    "khaki",
    "burgundy",
    "dark teal",
    "brick red",
    "royal purple",
    "plum",
    "mint green",
    "gold",
    "baby blue",
    "yellow green",
    "bright purple",
    "dark red",
    "pale blue",
    "grass green",
    "navy",
    "aquamarine",
    "burnt orange",
    "neon green",
    "bright blue",
    "rose",
    "light pink",
    "mustard",
    "indigo",
    "lime",
    "sea green",
    "periwinkle",
    "dark pink",
    "olive green",
    "peach",
    "pale green",
    "light brown",
    "hot pink",
    "black",
    "lilac",
    "navy blue",
    "royal blue",
    "beige",
    "salmon",
    "olive",
    "maroon",
    "bright green",
    "dark purple",
    "mauve",
    "forest green",
    "aqua",
    "cyan",
    "tan",
    "dark blue",
    "lavender",
    "turquoise",
    "dark green",
    "violet",
    "light purple",
    "lime green",
    "grey",
    "sky blue",
    "yellow",
    "magenta",
    "light green",
    "orange",
    "teal",
    "light blue",
    "red",
    "brown",
    "pink",
    "blue",
    "green",
    "purple",
]


colors_alph = [
    "acid green",
    "adobe",
    "algae green",
    "algae",
    "almost black",
    "amber",
    "amethyst",
    "apple green",
    "apple",
    "apricot",
    "aqua blue",
    "aqua green",
    "aqua marine",
    "aqua",
    "aquamarine",
    "army green",
    "asparagus",
    "aubergine",
    "auburn",
    "avocado green",
    "avocado",
    "azul",
    "azure",
    "baby blue",
    "baby green",
    "baby pink",
    "baby poo",
    "baby poop green",
    "baby poop",
    "baby puke green",
    "baby purple",
    "baby shit brown",
    "baby shit green",
    "banana yellow",
    "banana",
    "barbie pink",
    "barf green",
    "barney purple",
    "barney",
    "battleship grey",
    "beige",
    "berry",
    "bile",
    "black",
    "bland",
    "blood orange",
    "blood red",
    "blood",
    "blue blue",
    "blue green",
    "blue grey",
    "blue purple",
    "blue violet",
    "blue with a hint of purple",
    "blue",
    "blue/green",
    "blue/grey",
    "blue/purple",
    "blueberry",
    "bluegreen",
    "bluegrey",
    "bluey green",
    "bluey grey",
    "bluey purple",
    "bluish green",
    "bluish grey",
    "bluish purple",
    "bluish",
    "blurple",
    "blush pink",
    "blush",
    "booger green",
    "booger",
    "bordeaux",
    "boring green",
    "bottle green",
    "brick orange",
    "brick red",
    "brick",
    "bright ",
    "bright aqua",
    "bright blue",
    "bright cyan",
    "bright green",
    "bright lavender",
    "bright light blue",
    "bright light green",
    "bright lilac",
    "bright lime green",
    "bright lime",
    "bright magenta",
    "bright olive",
    "bright orange",
    "bright pink",
    "bright purple",
    "bright sea green",
    "bright sky blue",
    "bright teal",
    "bright turquoise",
    "bright violet",
    "bright yellow green",
    "bright yellow",
    "british racing green",
    "bronze",
    "brown green",
    "brown grey",
    "brown orange",
    "brown red",
    "brown yellow",
    "brown",
    "brownish green",
    "brownish grey",
    "brownish orange",
    "brownish pink",
    "brownish purple",
    "brownish red",
    "brownish yellow",
    "brownish",
    "browny green",
    "browny orange",
    "bruise",
    "bubble gum pink",
    "bubblegum pink",
    "bubblegum",
    "buff",
    "burgundy",
    "burnt orange",
    "burnt red",
    "burnt siena",
    "burnt sienna",
    "burnt umber",
    "burnt yellow",
    "burple",
    "butter yellow",
    "butter",
    "butterscotch",
    "cadet blue",
    "camel",
    "camo green",
    "camo",
    "camouflage green",
    "canary yellow",
    "canary",
    "candy pink",
    "caramel",
    "carmine",
    "carnation pink",
    "carnation",
    "carolina blue",
    "celadon",
    "celery",
    "cement",
    "cerise",
    "cerulean blue",
    "cerulean",
    "charcoal grey",
    "charcoal",
    "chartreuse",
    "cherry red",
    "cherry",
    "chestnut",
    "chocolate brown",
    "chocolate",
    "cinnamon",
    "claret",
    "clay brown",
    "clay",
    "clear blue",
    "cloudy blue",
    "cobalt blue",
    "cobalt",
    "cocoa",
    "coffee",
    "cool blue",
    "cool green",
    "cool grey",
    "copper",
    "coral pink",
    "coral",
    "cornflower blue",
    "cornflower",
    "cranberry",
    "cream",
    "creme",
    "crimson",
    "custard",
    "cyan",
    "dandelion",
    "dark aqua",
    "dark aquamarine",
    "dark beige",
    "dark blue green",
    "dark blue grey",
    "dark blue",
    "dark brown",
    "dark coral",
    "dark cream",
    "dark cyan",
    "dark forest green",
    "dark fuchsia",
    "dark gold",
    "dark grass green",
    "dark green blue",
    "dark green",
    "dark grey blue",
    "dark grey",
    "dark hot pink",
    "dark indigo",
    "dark khaki",
    "dark lavender",
    "dark lilac",
    "dark lime green",
    "dark lime",
    "dark magenta",
    "dark maroon",
    "dark mauve",
    "dark mint green",
    "dark mint",
    "dark mustard",
    "dark navy blue",
    "dark navy",
    "dark olive green",
    "dark olive",
    "dark orange",
    "dark pastel green",
    "dark peach",
    "dark periwinkle",
    "dark pink",
    "dark plum",
    "dark purple",
    "dark red",
    "dark rose",
    "dark royal blue",
    "dark sage",
    "dark salmon",
    "dark sand",
    "dark sea green",
    "dark seafoam green",
    "dark seafoam",
    "dark sky blue",
    "dark slate blue",
    "dark tan",
    "dark taupe",
    "dark teal",
    "dark turquoise",
    "dark violet",
    "dark yellow green",
    "dark yellow",
    "dark",
    "darkblue",
    "darkgreen",
    "darkish blue",
    "darkish green",
    "darkish pink",
    "darkish purple",
    "darkish red",
    "deep aqua",
    "deep blue",
    "deep brown",
    "deep green",
    "deep lavender",
    "deep lilac",
    "deep magenta",
    "deep orange",
    "deep pink",
    "deep purple",
    "deep red",
    "deep rose",
    "deep sea blue",
    "deep sky blue",
    "deep teal",
    "deep turquoise",
    "deep violet",
    "denim blue",
    "denim",
    "desert",
    "diarrhea",
    "dirt brown",
    "dirt",
    "dirty blue",
    "dirty green",
    "dirty orange",
    "dirty pink",
    "dirty purple",
    "dirty yellow",
    "dodger blue",
    "drab green",
    "drab",
    "dried blood",
    "duck egg blue",
    "dull blue",
    "dull brown",
    "dull green",
    "dull orange",
    "dull pink",
    "dull purple",
    "dull red",
    "dull teal",
    "dull yellow",
    "dusk blue",
    "dusk",
    "dusky blue",
    "dusky pink",
    "dusky purple",
    "dusky rose",
    "dust",
    "dusty blue",
    "dusty green",
    "dusty lavender",
    "dusty orange",
    "dusty pink",
    "dusty purple",
    "dusty red",
    "dusty rose",
    "dusty teal",
    "earth",
    "easter green",
    "easter purple",
    "ecru",
    "egg shell",
    "eggplant purple",
    "eggplant",
    "eggshell blue",
    "eggshell",
    "electric blue",
    "electric green",
    "electric lime",
    "electric pink",
    "electric purple",
    "emerald green",
    "emerald",
    "evergreen",
    "faded blue",
    "faded green",
    "faded orange",
    "faded pink",
    "faded purple",
    "faded red",
    "faded yellow",
    "fawn",
    "fern green",
    "fern",
    "fire engine red",
    "flat blue",
    "flat green",
    "fluorescent green",
    "fluro green",
    "foam green",
    "forest green",
    "forest",
    "forrest green",
    "french blue",
    "fresh green",
    "frog green",
    "fuchsia",
    "gold",
    "golden brown",
    "golden rod",
    "golden yellow",
    "golden",
    "goldenrod",
    "grape purple",
    "grape",
    "grapefruit",
    "grass green",
    "grass",
    "grassy green",
    "green apple",
    "green blue",
    "green brown",
    "green grey",
    "green teal",
    "green yellow",
    "green",
    "green/blue",
    "green/yellow",
    "greenblue",
    "greenish beige",
    "greenish blue",
    "greenish brown",
    "greenish cyan",
    "greenish grey",
    "greenish tan",
    "greenish teal",
    "greenish turquoise",
    "greenish yellow",
    "greenish",
    "greeny blue",
    "greeny brown",
    "greeny grey",
    "greeny yellow",
    "grey blue",
    "grey brown",
    "grey green",
    "grey pink",
    "grey purple",
    "grey teal",
    "grey",
    "grey/blue",
    "grey/green",
    "greyblue",
    "greyish blue",
    "greyish brown",
    "greyish green",
    "greyish pink",
    "greyish purple",
    "greyish teal",
    "greyish",
    "gross green",
    "gunmetal",
    "hazel",
    "heather",
    "heliotrope",
    "highlighter green",
    "hospital green",
    "hot green",
    "hot magenta",
    "hot pink",
    "hot purple",
    "hunter green",
    "ice blue",
    "ice",
    "icky green",
    "indian red",
    "indigo blue",
    "indigo",
    "iris",
    "irish green",
    "ivory",
    "jade green",
    "jade",
    "jungle green",
    "kelley green",
    "kelly green",
    "kermit green",
    "key lime",
    "khaki green",
    "khaki",
    "kiwi green",
    "kiwi",
    "lavender blue",
    "lavender pink",
    "lavender",
    "lawn green",
    "leaf green",
    "leaf",
    "leafy green",
    "leather",
    "lemon green",
    "lemon lime",
    "lemon yellow",
    "lemon",
    "lichen",
    "light aqua",
    "light aquamarine",
    "light beige",
    "light blue green",
    "light blue grey",
    "light blue",
    "light bluish green",
    "light bright green",
    "light brown",
    "light burgundy",
    "light cyan",
    "light eggplant",
    "light forest green",
    "light gold",
    "light grass green",
    "light green blue",
    "light green",
    "light greenish blue",
    "light grey blue",
    "light grey green",
    "light grey",
    "light indigo",
    "light khaki",
    "light lavendar",
    "light lavender",
    "light light blue",
    "light light green",
    "light lilac",
    "light lime green",
    "light lime",
    "light magenta",
    "light maroon",
    "light mauve",
    "light mint green",
    "light mint",
    "light moss green",
    "light mustard",
    "light navy blue",
    "light navy",
    "light neon green",
    "light olive green",
    "light olive",
    "light orange",
    "light pastel green",
    "light pea green",
    "light peach",
    "light periwinkle",
    "light pink",
    "light plum",
    "light purple",
    "light red",
    "light rose",
    "light royal blue",
    "light sage",
    "light salmon",
    "light sea green",
    "light seafoam green",
    "light seafoam",
    "light sky blue",
    "light tan",
    "light teal",
    "light turquoise",
    "light urple",
    "light violet",
    "light yellow green",
    "light yellow",
    "light yellowish green",
    "lightblue",
    "lighter green",
    "lighter purple",
    "lightgreen",
    "lightish blue",
    "lightish green",
    "lightish purple",
    "lightish red",
    "lilac",
    "liliac",
    "lime green",
    "lime yellow",
    "lime",
    "lipstick red",
    "lipstick",
    "macaroni and cheese",
    "magenta",
    "mahogany",
    "maize",
    "mango",
    "manilla",
    "marigold",
    "marine blue",
    "marine",
    "maroon",
    "mauve",
    "medium blue",
    "medium brown",
    "medium green",
    "medium grey",
    "medium pink",
    "medium purple",
    "melon",
    "merlot",
    "metallic blue",
    "mid blue",
    "mid green",
    "midnight blue",
    "midnight purple",
    "midnight",
    "military green",
    "milk chocolate",
    "mint green",
    "mint",
    "minty green",
    "mocha",
    "moss green",
    "moss",
    "mossy green",
    "mud brown",
    "mud green",
    "mud",
    "muddy brown",
    "muddy green",
    "muddy yellow",
    "mulberry",
    "murky green",
    "mushroom",
    "mustard brown",
    "mustard green",
    "mustard yellow",
    "mustard",
    "muted blue",
    "muted green",
    "muted pink",
    "muted purple",
    "nasty green",
    "navy blue",
    "navy green",
    "navy",
    "neon blue",
    "neon green",
    "neon pink",
    "neon purple",
    "neon red",
    "neon yellow",
    "nice blue",
    "night blue",
    "ocean blue",
    "ocean green",
    "ocean",
    "ocher",
    "ochre",
    "ocre",
    "off blue",
    "off green",
    "off white",
    "off yellow",
    "old pink",
    "old rose",
    "olive brown",
    "olive drab",
    "olive green",
    "olive yellow",
    "olive",
    "orange brown",
    "orange pink",
    "orange red",
    "orange yellow",
    "orange",
    "orangeish",
    "orangered",
    "orangey brown",
    "orangey red",
    "orangey yellow",
    "orangish brown",
    "orangish red",
    "orangish",
    "orchid",
    "pale aqua",
    "pale blue",
    "pale brown",
    "pale cyan",
    "pale gold",
    "pale green",
    "pale grey",
    "pale lavender",
    "pale light green",
    "pale lilac",
    "pale lime green",
    "pale lime",
    "pale magenta",
    "pale mauve",
    "pale olive green",
    "pale olive",
    "pale orange",
    "pale peach",
    "pale pink",
    "pale purple",
    "pale red",
    "pale rose",
    "pale salmon",
    "pale sky blue",
    "pale teal",
    "pale turquoise",
    "pale violet",
    "pale yellow",
    "pale",
    "parchment",
    "pastel blue",
    "pastel green",
    "pastel orange",
    "pastel pink",
    "pastel purple",
    "pastel red",
    "pastel yellow",
    "pea green",
    "pea soup green",
    "pea soup",
    "pea",
    "peach",
    "peachy pink",
    "peacock blue",
    "pear",
    "periwinkle blue",
    "periwinkle",
    "perrywinkle",
    "petrol",
    "pig pink",
    "pine green",
    "pine",
    "pink purple",
    "pink red",
    "pink",
    "pink/purple",
    "pinkish brown",
    "pinkish grey",
    "pinkish orange",
    "pinkish purple",
    "pinkish red",
    "pinkish tan",
    "pinkish",
    "pinky purple",
    "pinky red",
    "pinky",
    "piss yellow",
    "pistachio",
    "plum purple",
    "plum",
    "poison green",
    "poo brown",
    "poo",
    "poop brown",
    "poop green",
    "poop",
    "powder blue",
    "powder pink",
    "primary blue",
    "prussian blue",
    "puce",
    "puke brown",
    "puke green",
    "puke yellow",
    "puke",
    "pumpkin orange",
    "pumpkin",
    "pure blue",
    "purple blue",
    "purple brown",
    "purple grey",
    "purple pink",
    "purple red",
    "purple",
    "purple/blue",
    "purple/pink",
    "purpleish blue",
    "purpleish pink",
    "purpleish",
    "purpley blue",
    "purpley grey",
    "purpley pink",
    "purpley",
    "purplish blue",
    "purplish brown",
    "purplish grey",
    "purplish pink",
    "purplish red",
    "purplish",
    "purply blue",
    "purply pink",
    "purply",
    "putty",
    "racing green",
    "radioactive green",
    "raspberry",
    "raw sienna",
    "raw umber",
    "really light blue",
    "red brown",
    "red orange",
    "red pink",
    "red purple",
    "red violet",
    "red wine",
    "red",
    "reddish brown",
    "reddish grey",
    "reddish orange",
    "reddish pink",
    "reddish purple",
    "reddish",
    "reddy brown",
    "rich blue",
    "rich purple",
    "robin egg blue",
    "robin's egg blue",
    "robin's egg",
    "rosa",
    "rose pink",
    "rose red",
    "rose",
    "rosy pink",
    "rouge",
    "royal blue",
    "royal purple",
    "royal",
    "ruby",
    "russet",
    "rust brown",
    "rust orange",
    "rust red",
    "rust",
    "rusty orange",
    "rusty red",
    "saffron",
    "sage green",
    "sage",
    "salmon pink",
    "salmon",
    "sand brown",
    "sand yellow",
    "sand",
    "sandstone",
    "sandy brown",
    "sandy yellow",
    "sandy",
    "sap green",
    "sapphire",
    "scarlet",
    "sea blue",
    "sea green",
    "sea",
    "seafoam blue",
    "seafoam green",
    "seafoam",
    "seaweed green",
    "seaweed",
    "sepia",
    "shamrock green",
    "shamrock",
    "shit brown",
    "shit green",
    "shit",
    "shocking pink",
    "sick green",
    "sickly green",
    "sickly yellow",
    "sienna",
    "silver",
    "sky blue",
    "sky",
    "slate blue",
    "slate green",
    "slate grey",
    "slate",
    "slime green",
    "snot green",
    "snot",
    "soft blue",
    "soft green",
    "soft pink",
    "soft purple",
    "spearmint",
    "spring green",
    "spruce",
    "squash",
    "steel blue",
    "steel grey",
    "steel",
    "stone",
    "stormy blue",
    "straw",
    "strawberry",
    "strong blue",
    "strong pink",
    "sun yellow",
    "sunflower yellow",
    "sunflower",
    "sunny yellow",
    "sunshine yellow",
    "swamp green",
    "swamp",
    "tan brown",
    "tan green",
    "tan",
    "tangerine",
    "taupe",
    "tea green",
    "tea",
    "teal blue",
    "teal green",
    "teal",
    "tealish green",
    "tealish",
    "terra cotta",
    "terracota",
    "terracotta",
    "tiffany blue",
    "tomato red",
    "tomato",
    "topaz",
    "toupe",
    "toxic green",
    "tree green",
    "true blue",
    "true green",
    "turquoise blue",
    "turquoise green",
    "turquoise",
    "turtle green",
    "twilight blue",
    "twilight",
    "ugly blue",
    "ugly brown",
    "ugly green",
    "ugly pink",
    "ugly purple",
    "ugly yellow",
    "ultramarine blue",
    "ultramarine",
    "umber",
    "velvet",
    "vermillion",
    "very dark blue",
    "very dark brown",
    "very dark green",
    "very dark purple",
    "very light blue",
    "very light brown",
    "very light green",
    "very light pink",
    "very light purple",
    "very pale blue",
    "very pale green",
    "vibrant blue",
    "vibrant green",
    "vibrant purple",
    "violet blue",
    "violet pink",
    "violet red",
    "violet",
    "viridian",
    "vivid blue",
    "vivid green",
    "vivid purple",
    "vomit green",
    "vomit yellow",
    "vomit",
    "warm blue",
    "warm brown",
    "warm grey",
    "warm pink",
    "warm purple",
    "washed out green",
    "water blue",
    "watermelon",
    "weird green",
    "wheat",
    "white",
    "windows blue",
    "wine red",
    "wine",
    "wintergreen",
    "wisteria",
    "yellow brown",
    "yellow green",
    "yellow ochre",
    "yellow orange",
    "yellow tan",
    "yellow",
    "yellow/green",
    "yellowgreen",
    "yellowish brown",
    "yellowish green",
    "yellowish orange",
    "yellowish tan",
    "yellowish",
    "yellowy brown",
    "yellowy green",
]

beau_colors = colors
# import random
# random_colors = random.sample(colors, 20)
# print(list_of_random_items)